import lastmodJson from '@/data/lastmod.json';

// Generated by scripts/gen-lastmod.mjs (git commit dates). Never use a build
// timestamp for every URL — search engines learn to ignore it.
const routes = lastmodJson.routes as Record<string, string>;
const files = lastmodJson.files as Record<string, string>;

/** Latest git date among the given route keys ("/about", "/service-areas/[town]")
 *  and data-file keys ("src/data/serviceAreas.ts"). */
export function lastmod(...keys: string[]): Date {
  const dates = keys.map((k) => routes[k] ?? files[k]).filter(Boolean).sort();
  return new Date(dates.length ? dates[dates.length - 1] : lastmodJson.generatedAt);
}

/** Dynamic-route keys that serve arbitrary paths (checked in order after an exact match). */
const DYNAMIC: [RegExp, string][] = [
  [/^\/services\/[^/]+$/, '/services/[slug]'],
  [/^\/experiences\/categories\/[^/]+$/, '/experiences/categories/[category]'],
  [/^\/experiences\/[^/]+$/, '/experiences/[slug]'],
  [/^\/[^/]+$/, '/[slug]'],
];

/** Sitemap lastmod for a path: exact route date, else the dynamic route's date, else `fallback`. */
export function lastmodFor(path: string, fallback: string): Date {
  const exact = routes[path];
  if (exact) return new Date(exact);
  const dyn = DYNAMIC.find(([re]) => re.test(path))?.[1];
  if (dyn && routes[dyn]) return new Date(routes[dyn]);
  return new Date(fallback);
}
